# Set up the application. This file is required by
# google app engine so it can find the app to run

application: sharingcommons
version: 1
runtime: python27
api_version: 1
threadsafe: true

inbound_services:
- warmup

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
  
handlers:
- url: /
  script: src.app
- url: /static
  static_dir: src/static
- url: .*
  script: src.app

